# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "crates/swamp-render",
    "crates/swamp-app",
    "crates/swamp-wgpu-window",
    "crates/swamp-wgpu-sprites",
    "crates/swamp-wgpu",
]
